data = [
    {
        'PIN': '505230047',
        'LEGAL_DESC': 'BERK CTRY CLUB TERR #2 279',
        'expected_extraction': {'lot': '279', 'plat': 'BERK CTRY CLUB TERR #2'},
        'expected_regex_name': 'addition + lot (no labels)',
    },
    {
        'PIN': '508390006',
        'LEGAL_DESC': 'BAY VIEW PARK POR 5 9',
        'expected_extraction': {'lot': 'POR 5', 'plat': 'BAY VIEW PARK', 'block': '9'},
        'expected_regex_name': 'addition + lot + block no labels',
    },
    {
        'PIN': '570180021',
        'LEGAL_DESC': 'BERKELEY HIGHLANDS ADDN 22 P',
        'expected_extraction': {'lot': '22', 'plat': 'BERKELEY HIGHLANDS ADDN', 'block': 'P'},
        'expected_regex_name': 'addition + lot + block no labels',
    },
    {
        'PIN': '508390005',
        'LEGAL_DESC': 'BAY VIEW PARK 4 9',
        'expected_extraction': {'lot': '4', 'plat': 'BAY VIEW PARK', 'block': '9'},
        'expected_regex_name': 'addition + lot + block no labels',
    },
    {
        'PIN': '508390007',
        'LEGAL_DESC': 'BAY VIEW PARK POR 5&6 9',
        'expected_extraction': {'lot': 'POR 5&6', 'plat': 'BAY VIEW PARK', 'block': '9'},
        'expected_regex_name': 'addition + lot + block no labels',
    },
    {
        'PIN': '510031025',
        'LEGAL_DESC': 'RICHMOND ANNEX LOTS 34,35 & 36 BLK 95',
        'expected_extraction': {'lot': 'LOTS 34,35 & 36', 'plat': 'RICHMOND ANNEX', 'block': 'BLK 95'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '510115006',
        'LEGAL_DESC': 'RICHMOND ANNEX LOTS 10 & 11 BLK 88',
        'expected_extraction': {'lot': 'LOTS 10 & 11', 'plat': 'RICHMOND ANNEX', 'block': 'BLK 88'},
        'expected_regex_name': 'addition + lot + block',
    },   
    {
        'PIN': '513074017',
        'LEGAL_DESC': 'WALLS ADDN LOTS 31 & 32 BLK 170',
        'expected_extraction': {'lot': 'LOTS 31 & 32', 'plat': 'WALLS ADDN', 'block': 'BLK 170'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '509160013',
        'LEGAL_DESC': 'BAY VIEW PARK LTS 2&3 BLK 14',
        'expected_extraction': {'lot': 'LTS 2&3', 'plat': 'BAY VIEW PARK', 'block': 'BLK 14'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '509100012',
        'LEGAL_DESC': 'BAY VIEW PARK LOTS 10 TO 17 BLK 3',
        'expected_extraction': {'lot': 'LOTS 10 TO 17', 'plat': 'BAY VIEW PARK', 'block': 'BLK 3'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '087141008',
        'LEGAL_DESC': 'PITTSBURG HTS LOT 299 BLK 16',
        'expected_extraction': {'lot': 'LOT 299', 'plat': 'PITTSBURG HTS', 'block': 'BLK 16'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '357083001',
        'LEGAL_DESC': 'TOWN OF RODEO LOTS 1 & 3 BLK 22W',
        'expected_extraction': {'lot': 'LOTS 1 & 3', 'plat': 'TOWN OF RODEO', 'block': 'BLK 22W'},
        'expected_regex_name': 'addition + lot + block',
    },
    {
        'PIN': '503302011',
        'LEGAL_DESC': 'BERK CTRY CLUB TERR #1 LOT 234',
        'expected_extraction': {'lot': 'LOT 234', 'plat': 'BERK CTRY CLUB TERR #1'},
        'expected_regex_name': 'addition + lot (no block)',
    },
    {
        'PIN': '173012005',
        'LEGAL_DESC': 'WALDEN ACRES LOT 11 0.368 AC',
        'expected_extraction': {'lot': 'LOT 11', 'plat': 'WALDEN ACRES'},
        'expected_regex_name': 'addition + lot (no block)',
    },
    {
        'PIN': '173012008',
        'LEGAL_DESC': 'WALDEN ACRES LOT 9 & S 15 FT LOT 10',
        'expected_extraction': {'lot': 'LOT 9 & S 15 FT LOT 10', 'plat': 'WALDEN ACRES'},
        'expected_regex_name': 'addition + lot (no block)',
    },
    {
        'PIN': '173012007',
        'LEGAL_DESC': 'WALDEN ACRES N 81 FT LOT 10',
        'expected_extraction': {'lot': 'N 81 FT LOT 10', 'plat': 'WALDEN ACRES'},
        'expected_regex_name': 'addition + lot (no block)',
    },
    
    {
        'PIN': '380191002',
        'LEGAL_DESC': 'VALLE DEL SOL LOT 42',
        'expected_extraction': {'lot': 'LOT 42', 'plat': 'VALLE DEL SOL'},
        'expected_regex_name': 'addition + lot (no block)',
    },
    {
        'PIN': '510115022',
        'LEGAL_DESC': 'RICHMOND ANNEX LOT 35 POR 34 BLK 88',
        'expected_extraction': {'lot': 'LOT 35 POR 34', 'plat': 'RICHMOND ANNEX', 'block': 'BLK 88'},
        'expected_regex_name': 'addition + lot + por + block',
    },
    {
        'PIN': '173161013',
        'LEGAL_DESC': 'WALNUT PARK POR LOT 30 1.427 AC',
        'expected_extraction': {'lot': 'POR LOT 30', 'plat': 'WALNUT PARK'},
        'expected_regex_name': 'addition + por_lot simple (no block)',
    },
    {
        'PIN': '503141014',
        'LEGAL_DESC': 'SCHMIDT & FINK POR LOT 38',
        'expected_extraction': {'lot': 'POR LOT 38', 'plat': 'SCHMIDT & FINK'},
        'expected_regex_name': 'addition + por_lot simple (no block)',
    },
    {
        'PIN': '173161003',
        'LEGAL_DESC': 'WALNUT PARK POR LOTS 30 & 31 1.228 AC',
        'expected_extraction': {'lot': 'POR LOTS 30 & 31', 'plat': 'WALNUT PARK'},
        'expected_regex_name': 'addition + por_lot (no block)',
    },
    {
        'PIN': '411060011',
        'LEGAL_DESC': 'RICH PULLMAN PUEBLO LT 29 & POR 30 BLK 21',
        'expected_extraction': {'lot': 'LT 29 & POR 30', 'plat': 'RICH PULLMAN PUEBLO', 'block': 'BLK 21'},
        'expected_regex_name': 'addition + lot + por + block',
    },

    {
        'PIN': '508270022',
        'LEGAL_DESC': 'RICH ANNEX LOTS 42 & 43 POR 41 BLK 27',
        'expected_extraction': {'lot': 'LOTS 42 & 43 POR 41', 'plat': 'RICH ANNEX', 'block': 'BLK 27'},
        'expected_regex_name': 'addition + lot + por + block',
    },
    {
        'PIN': '505230019',
        'LEGAL_DESC': 'BERK CTRY CLUB TERR #1 LOT 259 POR 260',
        'expected_extraction': {'lot': 'LOT 259 POR 260', 'plat': 'BERK CTRY CLUB TERR #1'},
        'expected_regex_name': 'addition + lot + por (no block)',
    },
    {
        'PIN': '504300006',
        'LEGAL_DESC': 'CERRITO PARK TRACT LOT 9 POR 8 & 10 BLK 7',
        'expected_extraction': {'lot': 'LOT 9 POR 8 & 10', 'plat': 'CERRITO PARK TRACT', 'block': 'BLK 7'},
        'expected_regex_name': 'addition + lot + por + block',
    },
    {
        'PIN': '513322006',
        'LEGAL_DESC': 'UNION LOTS 20 & 21 POR 22 BLK D',
        'expected_extraction': {'lot': 'LOTS 20 & 21 POR 22', 'plat': 'UNION', 'block': 'BLK D'},
        'expected_regex_name': 'addition + lot + por + block',
    },
    {
        'PIN': '172130019',
        'LEGAL_DESC': 'LARKEY RANCH #1 POR LOT 44A',
        'expected_extraction': {'lot': 'POR LOT 44A', 'plat': 'LARKEY RANCH #1'},
        'expected_regex_name': 'addition + por_lot simple (no block)',
    },
    {
        'PIN': '504231018',
        'LEGAL_DESC': 'EAST BAY CENTER TRACT POR 6',
        'expected_extraction': {'lot': 'POR 6', 'plat': 'EAST BAY CENTER TRACT'},
        'expected_regex_name': 'addition + por_lot simple (no block)',
    },
    {
        'PIN': '172130069',
        'LEGAL_DESC': 'LARKEY RANCH #1 POR LOTS 44A & 45A',
        'expected_extraction': {'lot': 'POR LOTS 44A & 45A', 'plat': 'LARKEY RANCH #1'},
        'expected_regex_name': 'addition + por_lot (no block)',
    },
    {
        'PIN': '173090053',
        'LEGAL_DESC': 'WALNUT PARK POR LOT 2',
        'expected_extraction': {'lot': 'POR LOT 2', 'plat': 'WALNUT PARK'},
        'expected_regex_name': 'addition + por_lot simple (no block)',
    },
    {
        'PIN': '503256026',
        'LEGAL_DESC': 'BLVD GARDENS POR LOT 13 BLK 15',
        'expected_extraction': {'lot': 'POR LOT 13', 'plat': 'BLVD GARDENS', 'block': 'BLK 15'},
        'expected_regex_name': 'addition + por_lot simple + block',
    },
     {
        'PIN': '503244002',
        'LEGAL_DESC': 'BLVD GARDENS #1 POR LOT 1 BLK 18',
        'expected_extraction': {'lot': 'POR LOT 1', 'plat': 'BLVD GARDENS #1', 'block': 'BLK 18'},
        'expected_regex_name': 'addition + por_lot simple + block',
    },
    {
        'PIN': '503050013',
        'LEGAL_DESC': 'N BERK TERR POR LTS 22,23,24&25 BLK 32',
        'expected_extraction': {'lot': 'POR LTS 22,23,24&25', 'plat': 'N BERK TERR', 'block': 'BLK 32'},
        'expected_regex_name': 'addition + por_lot + block',
    },
    {
        'PIN': '504160036',
        'LEGAL_DESC': 'T8377 L1',
        'expected_extraction': {'lot': 'L1', 'plat': 'T8377'},
        'expected_regex_name': 'numeric tract + lot',
    },
    {
        'PIN': '155370082',
        'LEGAL_DESC': 'T8347 L10',
        'expected_extraction': {'lot': 'L10', 'plat': 'T8347'},
        'expected_regex_name': 'numeric tract + lot',
    },
    {
        'PIN': '169340012',
        'LEGAL_DESC': 'T04778 L0002 B',
        'expected_extraction': {'lot': 'L0002 B', 'plat': 'T04778'},
        'expected_regex_name': 'numeric tract + lot',
    },
    {
        'PIN': '503520052',
        'LEGAL_DESC': 'T03955 L000A B',
        'expected_extraction': {'lot': 'L000A B', 'plat': 'T03955'},
        'expected_regex_name': 'numeric tract + lot',
    },
    {
        'PIN': '035522019',
        'LEGAL_DESC': 'T06408 L0037 B EX 1/2 MR',
        'expected_extraction': {'lot': 'L0037 B', 'plat': 'T06408'},
        'expected_regex_name': 'numeric tract + lot',
    },
    {
        'PIN': '413041011',
        'LEGAL_DESC': 'TRACT 2622 LOT 36',
        'expected_extraction': {'lot': 'LOT 36', 'plat': 'TRACT 2622'},
        'expected_regex_name': 'numeric tract + lot long',
    },
    {
        'PIN': '403163002',
        'LEGAL_DESC': 'TRACT 2112 LOT 76',
        'expected_extraction': {'lot': 'LOT 76', 'plat': 'TRACT 2112'},
        'expected_regex_name': 'numeric tract + lot long',
    },
    {
        'PIN': '218125001',
        'LEGAL_DESC': 'TRACT 3648 LOT 59 EX MR',
        'expected_extraction': {'lot': 'LOT 59', 'plat': 'TRACT 3648'},
        'expected_regex_name': 'numeric tract + lot long',
    },
    
    {
        'PIN': '513133012',
        'LEGAL_DESC': 'TRACT 2972 LOT 21 BLK 3',
        'expected_extraction': {'lot': 'LOT 21', 'plat': 'TRACT 2972', 'block': 'BLK 3'},
        'expected_regex_name': 'numeric tract + lot long + block',
    },
    {
        'PIN': '513142028',
        'LEGAL_DESC': 'TRACT 2972 POR LOT 11 BLK 2',
        'expected_extraction': {'lot': 'POR LOT 11', 'plat': 'TRACT 2972', 'block': 'BLK 2'},
        'expected_regex_name': 'numeric tract + lot long + block',
    },
]
